extends Node
const lvl_3 = ['ace', 'act', 'add', 'age', 'air', 'all', 'and', 'ant', 'any', 'ape', 'apt', 'arc', 'arm', 'art', 'ash', 'ask', 'ate', 'bad', 'bag', 'bat', 'bay', 'bed', 'bee', 'beg', 'bet', 'big', 'bin', 'bit', 'bow', 'box', 'boy', 'bud', 'bug', 'bun', 'bus', 'but', 'buy', 'cab', 'can', 'cap', 'car', 'cat', 'cow', 'cry', 'cup', 'cut', 'day', 'den', 'dew', 'dig', 'dim', 'dip', 'dog', 'dot', 'dry', 'due', 'dug', 'ear', 'eat', 'egg', 'end', 'fan', 'far', 'fat', 'fax', 'fed', 'few', 'fig', 'fit', 'fix', 'fly', 'fog', 'for', 'fox', 'fun', 'fur', 'gap', 'gas', 'get', 'gig', 'got', 'gum', 'gun', 'gut', 'gym', 'had', 'ham', 'has', 'hat', 'hay', 'hen', 'her', 'hey', 'hid', 'him', 'hip', 'hit', 'hop', 'hot', 'how', 'hug', 'hut']
const lvl_4 = ['moan', 'cart', 'pain', 'slum', 'blot', 'mate', 'sock', 'orgy', 'carp', 'tech', 'root', 'worm', 'slug', 'claw', 'firm', 'feat', 'pump', 'down', 'thud', 'toss', 'abet', 'grim', 'toll', 'sore', 'lamp', 'pose', 'perk', 'mate', 'draw', 'flap', 'star', 'corn', 'sway', 'just', 'clue', 'able', 'feel', 'prep', 'heed', 'wick', 'drag', 'long', 'open', 'part', 'shit', 'bold', 'huge', 'soar', 'plus', 'pick', 'poor', 'feed', 'wise', 'dial', 'hang', 'zoom', 'deli', 'away', 'bear', 'howl', 'tail', 'mail', 'butt', 'heck', 'draw', 'herd', 'pump', 'tray', 'bean', 'urge', 'soda', 'pork', 'call', 'nude', 'exit', 'part', 'lace', 'odds', 'rein', 'cost', 'fund', 'find', 'sway', 'clam', 'crap', 'node', 'bare', 'fact', 'male', 'fake', 'ease', 'peak', 'dais', 'bond', 'doze', 'rink', 'gale', 'dawn', 'dour', 'wall']
const lvl_5 = ['creep', 'chair', 'punch', 'novel', 'cider', 'perch', 'quilt', 'prime', 'chart', 'harsh', 'cover', 'yacht', 'forgo', 'aloof', 'rocky', 'offer', 'evoke', 'bunch', 'favor', 'lodge', 'mixer', 'aging', 'value', 'piece', 'amass', 'crash', 'agent', 'crack', 'amish', 'flute', 'creme', 'snuff', 'jihad', 'faded', 'salty', 'relic', 'fruit', 'react', 'minor', 'split', 'issue', 'wharf', 'skull', 'drape', 'smoke', 'awake', 'brave', 'shave', 'nasal', 'silky', 'credo', 'weave', 'slope', 'yo-yo', 'drive', 'catch', 'stand', 'libel', 'cross', 'shale', 'horny', 'craze', 'plumb', 'board', 'judge', 'pulse', 'belch', 'riser', 'cloak', 'cough', 'sniff', 'candy', 'mount', 'drill', 'plain', 'frail', 'macro', 'right', 'diver', 'stack', 'overt', 'added', 'chirp', 'clout', 'bushy', 'shape', 'allot', 'olive', 'exalt', 'unzip', 'manly', 'grill', 'wrist', 'diary', 'moron', 'rinse', 'limit', 'drown', 'vault', 'audio']
const lvl_6 = ['enmity', 'quirky', 'school', 'climax', 'amount', 'at-bat', 'gossip', 'cosmos', 'swivel', 'hobble', 'hunter', 'nickel', 'scorer', 'armpit', 'master', 'gravel', 'circle', 'troupe', 'huddle', 'reason', 'absorb', 'wallet', 'handle', 'dearth', 'skewer', 'reform', 'futile', 'laptop', 'crease', 'floral', 'attack', 'sunset', 'summit', 'edible', 'cavity', 'savior', 'immune', 'burrow', 'replay', 'french', 'obtain', 'vandal', 'closer', 'duster', 'paddle', 'staple', 'squeal', 'codify', 'oblige', 'jigsaw', 'select', 'pollen', 'smelly', 'hectic', 'cuddle', 'evince', 'cackle', 'acuity', 'assist', 'random', 'binary', 'grated', 'convoy', 'rugged', 'halter', 'unlock', 'kimono', 'stream', 'crafty', 'shower', 'linear', 'dismay', 'worthy', 'flying', 'tumble', 'finger', 'coerce', 'oppose', 'bereft', 'renter', 'factor', 'button', 'cheese', 'addict', 'hebrew', 'assign', 'jagged', 'puzzle', 'tangle', 'fatten', 'harbor', 'bloody', 'dangle', 'sewage', 'square', 'viewer', 'ransom', 'poster', 'violin', 'define']
const lvl_7 = ['wriggle', 'horizon', 'extreme', 'charter', 'age-old', 'lockout', 'playing', 'pilings', 'droplet', 'zealous', 'calling', 'trumpet', 'anarchy', 'pertain', 'upscale', 'impasse', 'preside', 'acclaim', 'ingrain', 'interim', 'refusal', 'failure', 'measure', 'blender', 'rescind', 'bouncer', 'nominee', 'enclave', 'taliban', 'command', 'hanging', 'terrier', 'harvest', 'pitiful', 'vehicle', 'program', 'deviate', 'scholar', 'looting', 'handler', 'antique', 'senator', 'highway', 'deplore', 'correct', 'boyhood', 'numeral', 'brigade', 'cracker', 'moonlit', 'trouble', 'hostile', 'perform', 'traffic', 'snicker', 'crumble', 'attempt', 'content', 'redress', 'tsunami', 'related', 'uncover', 'cyanide', 'boulder', 'incense', 'rolling', 'balloon', 'destiny', 'rethink', 'lowland', 'sapling', 'deplete', 'capital', 'inflict', 'redhead', 'council', 'outdoor', 'climate', 'utopian', 'lacquer', 'fluency', 'grandma', 'violate', 'initial', 'pleated', 'special', 'whisker', 'daycare', 'connote', 'useless', 'respect', 'undress', 'one-day', 'airport', 'caribou', 'jewelry', 'besiege', 'dreaded', 'gaseous', 'hallway']
const lvl_8 = ['sedative', 'applause', 'blooming', 'distaste', 'backside', 'entangle', 'ranching', 'ponytail', 'newscast', 'baritone', 'lacrosse', 'prestige', 'disagree', 'workshop', 'leverage', 'maternal', 'database', 'position', 'feminist', 'seawater', 'backward', 'antidote', 'openness', 'artifice', 'spinning', 'reverend', 'traveler', 'withdraw', 'forecast', 'overview', 'overlook', 'redesign', 'low-wage', 'construe', 'footnote', 'meatball', 'medicine', 'encircle', 'junkyard', 'narrator', 'archival', 'hormonal', 'additive', 'big-city', 'campaign', 'bathrobe', 'backbone', 'blacktop', 'founding', 'rollover', 'disguise', 'obituary', 'epilepsy', 'cherokee', 'educated', 'dispatch', 'war-torn', 'essayist', 'inclined', 'fugitive', 'triangle', 'refinery', 'coercive', 'winnings', 'abnormal', 'scenario', 'covenant', 'overhead', 'flashing', 'enshrine', 'parisian', 'trailing', 'convince', 'heavenly', 'speaking', 'stinging', 'chestnut', 'protocol', 'airstrip', 'thinking', 'registry', 'promoter', 'parmesan', 'immortal', 'compound', 'baguette', 'airfield', 'strangle', 'priestly', 'retrieve', 'magnetic', 'vicinity', 'frontier', 'prophecy', 'original', 'occupant', 'celibate', 'populism', 'academia', 'workable']
const lvl_9 = ['coveralls', 'transport', 'dependent', 'personify', 'existence', 'apprehend', 'unplanned', 'biosolids', 'extremist', 'statement', 'gamma-ray', 'socialism', 'fluctuate', 'hand-held', 'insinuate', 'toothpick', 'attrition', 'foreigner', 'worshiper', 'anecdotal', 'voluntary', 'brainwash', 'three-day', 'microcosm', 'refurbish', 'ascending', 'underline', 'depressed', 'education', 'ice-cream', 'reflector', 'fragrance', 'communist', 'landscape', 'incumbent', 'fertilize', 'endurance', 'financier', 'severance', 'classical', 'responder', 'deafening', 'encounter', 'captivity', 'sumptuous', 'conducive', 'testament', 'assertion', 'dominance', 'harrowing', 'enumerate', 'pregnancy', 'devastate', 'organizer', 'impulsive', 'formative', 'prescribe', 'skyrocket', 'galvanize', 'hitchhike', 'dissident', 'congested', 'hamstring', 'recession', 'declining', 'defending', 'enjoyable', 'agreeable', 'stalemate', 'mammogram', 'geriatric', 'extensive', 'scripture', 'injection', 'paperwork', 'secondary', 'correlate', 'apartheid', 'establish', 'uncertain', 'germinate', 'perceived', 'sincerity', 'placement', 'prominent', 'reduction', 'sovereign', 'stylistic', 'infertile', 'truckload', 'craziness', 'foodstuff', 'enunciate', 'aesthetic', 'reservoir', 'thank-you', 'concierge', 'vandalism', 'checkered', 'difficult']
const lvl_10 = ['censorship', 'sprinkling', 'satisfying', 'chromosome', 'unyielding', 'councilman', 'purposeful', 'competitor', 'periodical', 'imaginable', 'ventilator', 'brownstone', 'translator', 'tree-lined', 'credential', 'hemisphere', 'refinement', 'strawberry', 'collateral', 'accounting', 'speculator', 'videotaped', 'geothermal', 'simplified', 'vernacular', 'permissive', 'late-night', 'unintended', 'inflection', 'convection', 'aspiration', 'pragmatist', 'separating', 'concluding', 'recitation', 'comparison', 'underclass', 'instructor', 'capitalist', 'unoccupied', 'round-trip', 'distraught', 'standpoint', 'evaluation', 'bitterness', 'internment', 'illustrate', 'advertiser', 'overworked', 'foreshadow', 'monogamous', 'wastewater', 'horsepower', 'individual', 'windowless', 'commitment', 'synthesize', 'persuasive', 'pernicious', 'moderation', 'absorption', 'monotonous', 'reluctance', 'anesthesia', 'reconsider', 'regressive', 'settlement', 'prediction', 'wavelength', 'chancellor', 'speechless', 'confiscate', 'cornerback', 'embodiment', 'elliptical', 'continuity', 'enterprise', 'uneducated', 'simulation', 'girlfriend', 'senatorial', 'memorandum', 'priesthood', 'affordable', 'self-doubt', 'undetected', 'top-ranked', 'unsettling', 'acceptable', 'republican', 'internship', 'lieutenant', 'undercover', 'smattering', 'supportive', 'expatriate', 'principled', 'admiration', 'acceptance', 'guatemalan']
const word_dictionary = {
	3: lvl_3,
	4: lvl_4,
	5: lvl_5,
	6: lvl_6,
	7: lvl_7,
	8: lvl_8,
	9: lvl_9,
	10: lvl_10
}


func get_word(amount = 1):
	var rng = RandomNumberGenerator.new()
	rng.randomize()
	var word_index_arr: Array[int] = []
	word_index_arr.resize(amount)
	word_index_arr.fill(-1)
	for n in range(amount):
		var ran_num = rng.randi_range(0,99)
		while ran_num in word_index_arr:
			ran_num = rng.randi_range(0,99)
		word_index_arr[n] = ran_num
	return word_index_arr
